// AUTO-GENERATED. AI-generated recipe instructions approved by the user.
// Do not edit by hand; regenerated from approved entries.

export const GENERATED_INSTRUCTIONS: Record<string, string> = {
  "Alcachofas": "1. Limpia las alcachofas: retira las hojas exteriores más duras, corta las puntas y pela el tallo dejando el corazón. Pártelas por la mitad o en cuartos y déjalas en agua con limón para que no se oxiden.\n2. Escúrrelas y sécalas bien. Ponlas en un cazo y cúbrelas con aceite de oliva virgen extra. Añade unos dientes de ajo, una pizca de sal y, si quieres, laurel o tomillo.\n3. Confita a fuego muy bajo (el aceite debe burbujear apenas, sin freír) durante 35-45 minutos, hasta que estén tiernas al pincharlas. Deja templar en el aceite.\n4. Calienta una plancha o sartén a fuego fuerte. Escurre las alcachofas y dóralas por ambos lados 2-3 minutos, hasta que queden crujientes y marcadas.\n5. Sírvelas calientes con sal en escamas y un hilo del propio aceite de confitar.",
  "Arroz a la milanesa": "1. Limpia y lamina los champiñones. Saltéalos en una sartén con un poco de aceite o mantequilla hasta que pierdan el agua y se doren. Reserva.\n2. En una cazuela, rehoga el arroz un par de minutos para que se nacare.\n3. Añade un buen chorro de vino blanco y deja que se evapore el alcohol.\n4. Ve añadiendo caldo caliente poco a poco, sin dejar de remover, hasta que el arroz esté cremoso y en su punto (unos 18 minutos).\n5. Incorpora los champiñones salteados y, fuera del fuego, una buena cantidad de queso rallado fuerte tipo parmesano. Mezcla bien.\n6. Sirve enseguida con más queso rallado por encima.",
  "Arroz blanco con tomate y jamón York": "1. Prepara un tomate frito casero: pocha un poco de cebolla o ajo en aceite, añade el tomate triturado, una pizca de sal y de azúcar, y deja reducir a fuego medio hasta que espese.\n2. Cuece el arroz en abundante agua con sal y un par de dientes de ajo durante unos 15-18 minutos. Escúrrelo.\n3. Saltea los taquitos de jamón York un par de minutos en una sartén con unas gotas de aceite.\n4. Sirve el arroz blanco (puedes moldearlo) y cúbrelo con el tomate frito caliente y el jamón York por encima.",
  "Atún con tomate": "1. Salpimienta los lomos de atún fresco y dóralos vuelta y vuelta en una plancha o sartén bien caliente con unas gotas de aceite, dejándolos jugosos por dentro. Reserva.\n2. Pica finamente la cebolla y póchala a fuego lento en una sartén con aceite de oliva hasta que esté tierna y transparente.\n3. Añade el tomate triturado, una pizca de sal y un poco de azúcar para corregir la acidez. Cocina a fuego medio unos 15-20 minutos, hasta que reduzca y espese.\n4. Corta el atún en trozos e incorpóralo a la salsa. Cocina un par de minutos más, solo para que se integre, sin que se reseque.\n5. Rectifica de sal y sirve, espolvoreado con perejil picado.",
  "Berenjenas con mozzarella": "1. Lava las berenjenas y córtalas por la mitad a lo largo. Haz unos cortes en cruz en la carne, sin llegar a la piel, y úntalas con un poco de aceite y sal.\n2. Ásalas en el horno a 200°C, con la carne hacia arriba, unos 25-30 minutos, hasta que estén tiernas.\n3. Mientras, prepara un sofrito de tomate: pocha cebolla picada, añade el tomate triturado, sal y un poco de azúcar, y deja reducir.\n4. Reparte el sofrito de tomate sobre las medias berenjenas asadas y cubre con mozzarella en lonchas o rallada.\n5. Gratina en el horno hasta que el queso se funda y se dore por encima. Sirve caliente.",
  "Boquerones fritos": "1. Limpia los boquerones: quítales la cabeza y las tripas y, si quieres, la espina central. Lávalos y sécalos bien.\n2. Sálalos y pásalos por harina (mejor harina especial para freír), sacudiendo el exceso.\n3. Calienta abundante aceite de oliva en una sartén. Cuando esté bien caliente, fríe los boquerones por tandas, sin amontonarlos, hasta que estén dorados y crujientes.\n4. Escúrrelos sobre papel de cocina.\n5. Sírvelos enseguida con unos gajos de limón.",
  "Brócoli con mayonesa": "1. Separa el brócoli en ramilletes y lávalos bien.\n2. Cuécelos al vapor o en agua hirviendo con sal entre 5 y 8 minutos, hasta que estén tiernos pero todavía firmes y de color verde vivo. Escúrrelos.\n3. Prepara una mayonesa casera: pon en el vaso de la batidora un huevo, el zumo de medio limón y media cucharadita de sal, y bate todo junto. Sin dejar de batir, ve añadiendo el aceite poco a poco hasta que emulsione y espese.\n4. Sirve el brócoli templado o frío con la mayonesa al lado o por encima.",
  "Calabacín con tomate arcoiris": "1. Lava el calabacín y los tomates y córtalos en rodajas finas.\n2. Engrasa una fuente de horno y ve colocando las rodajas alternando calabacín y tomate, en filas, formando el efecto \"arcoíris\". Sala ligeramente.\n3. Riega con la nata líquida por encima.\n4. Cubre con queso rallado y queso gouda o havarti en lonchas.\n5. Hornea a 190°C unos 30-35 minutos, hasta que el calabacín esté tierno y el queso dorado y gratinado. Sirve caliente.",
  "Calamares fritos": "1. Limpia los calamares y córtalos en anillas. Sécalas bien con papel de cocina.\n2. Sálalas y pásalas por harina (mejor harina especial para freír), sacudiendo el exceso. Si te gustan más jugosos, puedes pasarlos antes por leche o por huevo batido.\n3. Calienta abundante aceite de oliva en una sartén hasta que esté bien caliente.\n4. Fríe las anillas por tandas, sin amontonarlas, 1-2 minutos, hasta que estén doradas y crujientes.\n5. Escúrrelas sobre papel de cocina y sírvelas enseguida con gajos de limón.",
  "Carne guisada": "1. Salpimienta la ternera en dados, enharínala ligeramente y dórala en una cazuela con aceite caliente. Reserva.\n2. En la misma cazuela, pocha cebolla picada (y un poco de ajo) hasta que esté tierna. Añade las zanahorias en rodajas y los champiñones laminados y rehoga unos minutos.\n3. Devuelve la carne a la cazuela. Riega con un chorro de vino blanco y deja evaporar el alcohol.\n4. Cubre con caldo o agua, añade una hoja de laurel y sal, y guisa a fuego lento entre 1 hora y 1 hora y media, hasta que la carne esté muy tierna y la salsa haya espesado.\n5. Rectifica de sal y sirve caliente.",
  "Chuleta de Sajonia": "1. Calienta una plancha o sartén a fuego fuerte con unas gotas de aceite.\n2. Marca las chuletas de Sajonia (cinta de lomo adobada/ahumada) vuelta y vuelta, 1-2 minutos por cada lado, hasta que estén doradas y marcadas pero jugosas (ya vienen curadas, no necesitan mucha cocción).\n3. Sírvelas calientes. Acompáñalas, si quieres, con patatas o una ensalada.",
  "Cinta de lomo": "1. Salpimienta los filetes de cinta de lomo. Si quieres, úntalos con un poco de ajo y aceite.\n2. Calienta una plancha o sartén a fuego fuerte con unas gotas de aceite.\n3. Marca los filetes 2-3 minutos por cada lado, hasta que estén dorados por fuera y jugosos por dentro (sin pasarlos para que no queden secos).\n4. Sírvelos calientes, con unas gotas de limón o la guarnición que prefieras.",
  "Cogollos con anchoas": "1. Lava los cogollos, sécalos y córtalos por la mitad (o en cuartos si son grandes).\n2. Colócalos en una fuente con el corte hacia arriba.\n3. Reparte las anchoas por encima de cada mitad.\n4. Añade unas lascas de queso curado fuerte por encima.\n5. Aliña con un buen chorro de aceite de oliva virgen extra. Si quieres, añade unas gotas de vinagre o limón. No suele hacer falta sal por el punto salado de las anchoas y el queso.\n6. Sirve frío, recién aliñado.",
  "Consomé": "1. Pon en una olla grande el hueso, el medio pollo, el trozo de ternera y las zanahorias. Cubre con abundante agua y añade sal.\n2. Lleva a ebullición y retira la espuma que suba a la superficie. Baja el fuego.\n3. Cuece a fuego lento al menos 1 hora y media o 2 horas, para que el caldo coja sabor y quede limpio.\n4. Cuela el caldo. Desgrasa si quieres pasándolo por un colador fino o retirando la grasa de la superficie.\n5. Vuelve a poner el caldo al fuego, llévalo a hervor suave y cuece las estrellitas el tiempo que indique el paquete (unos 5-7 minutos).\n6. Rectifica de sal y sirve caliente.",
  "Dorada o lubina a la sal": "1. Precalienta el horno a 200°C. Limpia las doradas o lubinas (sin escamar, solo eviscerar) y sécalas.\n2. En una bandeja de horno, pon una cama de sal gorda ligeramente humedecida. Coloca un papel de horno sobre la sal y, encima, el pescado; así la piel no se queda pegada a la sal. Cúbrelo por completo con más sal gorda, dejando solo la cabeza asomando si quieres.\n3. Hornea unos 25-30 minutos (según el tamaño): calcula aproximadamente 20-25 minutos por kilo.\n4. Saca del horno, rompe la costra de sal con cuidado (dará un golpe seco) y retírala junto con el papel y la piel.\n5. Saca los lomos limpios y sírvelos con un hilo de aceite de oliva y unas gotas de limón.",
  "Ensalada caprese": "1. Corta la mozzarella (o burrata) y los tomates RAF en rodajas de un grosor similar. Si usas burrata, puedes ponerla entera en el centro y abrirla al servir.\n2. Colócalos en un plato alternando una rodaja de tomate y una de mozzarella, ligeramente montadas.\n3. Reparte unas hojas de albahaca fresca entre las rodajas.\n4. Aliña con un buen chorro de aceite de oliva virgen extra y una pizca de sal. Si te gusta, añade un poco de vinagre balsámico o unas cucharadas de salsa pesto por encima.\n5. Sirve enseguida, a temperatura ambiente.",
  "Ensalada de espinacas": "1. Prepara la cebolla confitada: corta la cebolla en juliana y rehógala a fuego lento en una sartén con un poco de aceite. Cuando esté tierna, añade una cucharada de azúcar y un chorrito de vinagre de Módena y cocina removiendo hasta que quede melosa y caramelizada. Deja templar.\n2. Lava bien las espinacas baby y escúrrelas. Ponlas como base en una ensaladera o plato.\n3. Reparte por encima el queso de cabra en rodajas o cuadraditos, el salmón ahumado en trozos, los anacardos y las pasas.\n4. Añade la cebolla confitada repartida por la ensalada.\n5. Aliña con aceite de oliva virgen extra, una pizca de sal y, si te gusta, un chorrito de vinagre de Módena o miel.\n6. Sirve recién aliñada.",
  "Ensalada de rúcula": "1. Lava la rúcula y escúrrela bien. Ponla como base en un plato o ensaladera.\n2. Lava los tomatitos cherry y córtalos por la mitad. Repártelos por encima. En lugar de los tomatitos cherry, también puedes añadir almendras fritas.\n3. Añade lascas de queso curado por toda la ensalada. Cuanto más fuerte sea el queso, mejor; también vale queso de oveja o de cabra curado.\n4. Aliña con un buen chorro de aceite de oliva virgen extra, una pizca de sal y, si te gusta, unas gotas de vinagre de Módena.\n5. Sirve recién aliñada.",
  "Ensalada de verano": "1. Cuece el huevo unos 10 minutos, refréscalo, pélalo y córtalo en gajos.\n2. Lava los tomates de ensalada y córtalos en rodajas. Disponlos como base en una fuente.\n3. Reparte por encima el atún escurrido, las aceitunas verdes, los palmitos en rodajas y la cebolla dulce en aros finos.\n4. Coloca los gajos de huevo duro alrededor.\n5. Aliña con aceite de oliva virgen extra y una pizca de sal. Sirve fría.",
  "Ensalada gourmet": "1. Lava la mezcla de ensalada gourmet y escúrrela bien. Ponla como base en una fuente.\n2. Pela y corta el aguacate en pedacitos (cubitos pequeños) y repártelo por encima.\n3. Añade el queso (curado o azul) en trocitos, los anacardos o nueces, los arándanos deshidratados (secos) y las bayas de Goji.\n4. Aliña con aceite de oliva virgen extra, una pizca de sal y, si te gusta, una vinagreta suave o unas gotas de vinagre de Módena.\n5. Sirve recién aliñada.",
  "Ensalada griega": "1. Lava las verduras. Corta los tomates en gajos, el pepino en medias rodajas y el pimiento verde en tiras o trozos. Corta la cebolla en aros finos.\n2. Ponlo todo en una ensaladera y mézclalo.\n3. Añade las aceitunas negras y el queso feta en dados repartido por la ensalada.\n4. Aliña con un buen chorro de aceite de oliva virgen extra, una pizca de sal y orégano. Si te gusta, unas gotas de vinagre.\n5. Sirve fría.",
  "Ensaladilla rusa": "1. Cuece el huevo unos 10 minutos. Pélalo y córtalo en gajos.\n2. Vuelca en un bol la bolsa de ensaladilla (patata y verduras ya cocidas) y escúrrela si lleva líquido.\n3. Añade el atún escurrido y las aceitunas.\n4. Prepara una mayonesa casera: pon en el vaso de la batidora un huevo, el zumo de medio limón y media cucharadita de sal, y bate todo junto. Sin dejar de batir, ve añadiendo el aceite poco a poco hasta que emulsione y espese. Usa aceite de oliva suave de 0,4º (no de oliva virgen, que amarga la mayonesa).\n5. Mezcla todo con abundante mayonesa hasta que quede bien cremoso y blanco. Rectifica de sal.\n6. Alísala en una fuente, decora con los gajos de huevo y aceitunas y sírvela bien fría.",
  "Espaguetis": "1. Prepara una salsa de tomate: pocha un poco de cebolla o ajo en aceite, añade el tomate triturado, sal y una pizca de azúcar, y deja reducir a fuego medio hasta que espese.\n2. Cuece los espaguetis en abundante agua con sal el tiempo que indique el paquete, hasta que estén al dente. Escúrrelos.\n3. Mezcla los espaguetis con la salsa de tomate caliente.\n4. Sirve con abundante queso rallado por encima.",
  "Filetes de ternera a la plancha": "1. Saca los filetes de ternera de la nevera un rato antes para que estén a temperatura ambiente. Sécalos con papel de cocina.\n2. Calienta una plancha o sartén a fuego fuerte con unas gotas de aceite.\n3. Marca los filetes vuelta y vuelta, poco tiempo por cada lado. No los hagas demasiado: sobre todo si la carne es de buena calidad, quedan mucho mejor un poco al punto, jugosos y algo rosados por dentro.\n4. Sálalos al sacarlos (mejor al final, para que no suelten los jugos).\n5. Sírvelos enseguida, con la guarnición que prefieras.",
  "Gazpacho": "1. Lava las verduras. Trocea los tomates, el pepino (pelado si quieres), los pimientos y pela los ajos.\n2. Pon todo en el vaso de la batidora con sal, un buen chorro de aceite de oliva virgen extra y un chorrito de vinagre.\n3. Tritura muy bien hasta que quede fino. Si te gusta más suave, pásalo por un colador o chino.\n4. Prueba y ajusta de sal, vinagre y aceite. Si está muy espeso, añade un poco de agua fría.\n5. Enfríalo en la nevera al menos un par de horas. Sírvelo bien frío, con verduritas picadas por encima si quieres.",
  "Guisantes con jamón": "1. Pica la cebolla finamente y póchala a fuego lento en una sartén con aceite de oliva hasta que esté tierna.\n2. Incorpora los guisantes (frescos o congelados) y saltea un par de minutos.\n3. Añade un poco de agua o caldo, tapa y cocina a fuego medio hasta que los guisantes estén tiernos (unos 10-15 minutos).\n4. Justo al final, añade los mini taquitos de jamón serrano y dales solo un golpe de calor, muy poco tiempo: si el jamón se cocina demasiado, se cuece y se endurece.\n5. Rectifica de sal con cuidado (el jamón ya aporta sal) y sirve caliente.",
  "Huevos con bechamel": "1. Cuece los huevos unos 10 minutos. Pélalos y córtalos en cuartos (gajos).\n2. Prepara una bechamel espesa: derrite mantequilla, incorpora la harina y cocínala un par de minutos. Vierte la leche caliente poco a poco sin dejar de remover, hasta obtener una bechamel densa. Salpimienta.\n3. Cubre cada gajo de huevo con una buena capa de bechamel, dándole forma alargada tipo croqueta. Colócalos en un plato y déjalos enfriar bien en la nevera para que la bechamel cuaje (mejor un par de horas).\n4. Pasa los huevos rebozados por huevo batido y luego por pan rallado.\n5. Fríelos en abundante aceite caliente hasta que estén dorados y crujientes por fuera.\n6. Escúrrelos sobre papel de cocina y sírvelos calientes.",
  "Huevos fritos con patatas": "1. Pela las patatas y córtalas en bastones. Fríelas en abundante aceite caliente hasta que estén tiernas y doradas. Escúrrelas y sálalas.\n2. Fríe los huevos de uno en uno en abundante aceite de oliva virgen bien caliente, dejando la yema líquida y la clara con las puntillas crujientes.\n3. Sirve los huevos sobre la cama de patatas, con el jamón serrano repartido por encima. Si quieres, rómpelos para mezclar la yema con las patatas.",
  "Huevos revueltos con jamón y champiñones": "1. Limpia y lamina los champiñones. Saltéalos en una sartén con un poco de aceite hasta que pierdan el agua y se doren.\n2. Añade los mini taquitos de jamón Serrano y dales solo un golpe de calor.\n3. Bate los huevos con una pizca de sal y viértelos en la sartén sobre los champiñones y el jamón.\n4. Cuaja los huevos a fuego suave, removiendo, hasta que queden cremosos y poco hechos.\n5. Sirve enseguida, con perejil picado si quieres."
};
